language: bash

before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck
  - sudo apt-get install imagemagick 
  - sudo apt-get install p7zip-full

script:
  - ls -l


notifications:
  email:
    on_success: never
